#! /usr/bin/python2.6
#  -*- coding: utf-8 -*-
from distutils.core import setup, Extension
setup(name='pyplanets_calculations', version='1.0', ext_modules=[Extension("pyplanets_calculations", ["./lib/pyplanets_calculations_module.c"])])
